{
 "title": "98 - COVID19 BRASIL",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "group", "query": "HOMOLOGACAO" },
   { "name": "host", "query": "$group.BRASIL-CORONA-COVID19" },
   { "name": "countries", "label": "Estados", "query": "$group.$host.*" },
   { "name": "casos", "query": "$group.$host.*.*" }
  ]
 },
 "panels": [
  { "title": "Estatisticas Mundiais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": { "filter": "Total All updated" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 18, "x": 3, "y": 1 },
   "content": "<div class=\"text-center\"> <img src=\"/public/img/linetwork.png\" width=\"15%\" height=\"35%\" />\n<h1 style=\"line-height: 45px; margin: 0; color: #bbb;\">LINETWORK SOLUÇÕES TECNOLOGICAS</h1><h3></a>Fonte de Dados: <a href=\"http://plataforma.saude.gov.br/novocoronavirus\" target=\"_blank\">http://plataforma.saude.gov.br/novocoronavirus</a><br>Obs: Dados contidos nesta Dashboard são para fins de testes da ferramenta</h3>\n</div>"
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": { "filter": "Total All Recovered" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": { "filter": "Total All Cases" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "application": { "filter": "Total Cases" },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": { "filter": "Total All Deaths" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Estatísticas Brasil", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "application": {
      "filter": "/.* \"Brazil\"/"
     },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": {
      "filter": "\"Brazil\" - ActiveCases"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Estados com Casos Suspeitos",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "/Casos .*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*)\" - Suspeitos/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*)\" - Suspeitos/, $1)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - Suspeitos/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Casos por Estados",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 6, "x": 12, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"([^.]*)\" - Casos/",
        "$1"
       ],
       "text": "replaceAlias(/\"([^.]*)\" - Casos/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$casos\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Obtos Estados",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"([^.]*)\" - Mortes/",
        "$1"
       ],
       "text": "replaceAlias(/\"([^.]*)\" - Mortes/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$casos\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "targets": [
    {
     "application": {
      "filter": "Cases \"Brazil\""
     },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": {
      "filter": "\"Brazil\" - Recovered"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Estados com Obitos",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "/Casos .*/" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*)\" - Mortes/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*)\" - Mortes/, $1)"
      },
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - Mortes/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "targets": [
    {
     "application": {
      "filter": "/.* \"Brazil\"/"
     },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": {
      "filter": "\"Brazil\" - TodayCases"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
   "targets": [
    {
     "application": {
      "filter": "Cases \"Brazil\""
     },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": {
      "filter": "\"Brazil\" - Critical"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOP 10 - Estados com Casos Comprovados",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 3, "y": 17 },
   "targets": [
    {
     "application": { "filter": "/Casos .*/" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "top",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "10",
        "avg"
       ],
       "text": "top(10, avg)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/\"(.*)\" - Casos/",
        "$1"
       ],
       "text": "replaceAlias(/\"(.*)\" - Casos/, $1)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/.* - Casos/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "targets": [
    {
     "application": {
      "filter": "Cases \"Brazil\""
     },
     "group": { "filter": "$group" },
     "host": { "filter": "CORONA-COVID19" },
     "item": {
      "filter": "\"Brazil\" - Deaths"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Estatisticas Estado - $countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "countries"
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Suspeitos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Negativos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Ultima Atualizacao Official/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Estatisticas Estado - $countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Suspeitos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Negativos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 32 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Ultima Atualizacao Official/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Estatisticas Estado - $countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Suspeitos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Negativos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Ultima Atualizacao Official/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Estatisticas Estado - $countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Suspeitos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 42 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Negativos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 42 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Ultima Atualizacao Official/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Estatisticas Estado - $countries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Casos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 47 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Suspeitos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 47 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Mortes/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 47 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Negativos/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 47 },
   "targets": [
    {
     "aggregation": "Last",
     "application": {
      "filter": "/Casos \"$countries\"/"
     },
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/\"$countries\" - Ultima Atualizacao Official/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}